name: Android Debug Build

on:
  workflow_dispatch: {}         # run manually
  push:
    branches: [ main ]          # auto-run on push to main (optional)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node is needed to run "npx cap sync android"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install npm dependencies
        run: npm ci || npm install

      # Generate native plugin files (this fixes the missing cordova.variables.gradle)
      - name: Capacitor sync
        run: |
          mkdir -p android/app/src/main/assets/public
          npx cap sync android
          echo "List generated folder:"
          ls -la android/capacitor-cordova-android-plugins || true

      # Java + Android SDK for Gradle build
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install build tools
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
